spring:
  datasource:
    url: jdbc:mysql://localhost:3306/citizen
    username: root
    password: Venkat_147
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

cloud:
  aws:
    credentials:
     access-key: 
     secret-key: 
    region:
      static: ap-south-1
    stack:
      auto: false
      
application:
  bucket:
    name:       
        
